MinaBilder3.0/Models/Credentials.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MinaBilder3._0.Models
{
    public class Credentials
    {
        public string Username { get; set; }
        public string Password { get; set; }

    }
}

MinaBilder3.0/Models/UploadModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MinaBilder3._0.Models
{
    public class UploadModel
    {
        
        public string Titel { get; set; }
        public string Kommentar { get; set; }
        public string Path { get; set; }

    }
}

MinaBilder3.0/Controllers/ImagesController.cs
using MinaBilder3._0;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mina_Bilder.Controllers
{
    public class ImagesController : Controller
    {
        // GET: Images
        public ActionResult Index()
        {
            //skapar en lista med bildernas sökväg, titel och kommentarer för att sedan loopas genom
            //i view och "stoppas" in i ett plugin som heter Lightbox som är från http://ashleydw.github.io/lightbox/
            List<Images> imageList = new List<Images>();
            using (ImagesModel db = new ImagesModel())
            {
                imageList = (from i in db.Images
                             select i).ToList(); 

            }
            return View(imageList); 
        }
    }
}

MinaBilder3.0/Controllers/LoginController.cs
using MinaBilder3._0;
using MinaBilder3._0.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Mina_Bilder.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Index(Credentials creds)
        {

            if (creds.Username == null || creds.Password == null)
            {
                ModelState.AddModelError("", "Fyll i både användarnamn och lösenord");
                return View();
            }

            bool userChecked = false;
            userChecked = credentialsCheck(creds.Username, creds.Password);

            if (userChecked == true)
            {
                System.Web.Security.FormsAuthentication.RedirectFromLoginPage(creds.Username, false);
            }
            return View();

        }

        private bool credentialsCheck(string Username, string Password)
        {
            using (ImagesModel db = new ImagesModel())
            {

                var credCheck = from c in db.Users
                                where c.Username == Username
                                && c.Password == Password
                                select c;
                if (credCheck.Count() == 1)
                {
                    return true;
                }
                else
                {
                    ViewBag.LoggedInFail = true;
                    return false;
                }
            }
        }
        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Start");
        }

    }


}


MinaBilder3.0/Controllers/RegisterController.cs
using MinaBilder3._0;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mina_Bilder.Controllers
{
    public class RegisterController : Controller
    {
        // GET: Register
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Users newUser)
        {
            if (ModelState.IsValid)
            {
                //Sparar ett object av en ny användare
                using (ImagesModel db = new ImagesModel())
                {
                    db.Users.Add(newUser);
                    db.SaveChanges();
                    ModelState.Clear();
                    newUser = null;
                    ViewBag.SuccessResult = true;
                }
            }
            return View();
        }
    }
}

MinaBilder3.0/Controllers/StartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mina_Bilder.Controllers
{
    public class StartController : Controller
    {
        // GET: Start
        public ActionResult Index()
        {
            return View();
        }
    }
}

MinaBilder3.0/Controllers/UploadController.cs
using MinaBilder3._0;
using MinaBilder3._0.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;


//http://www.aurigma.com/upload-suite/developers/aspnet-mvc/how-to-upload-files-in-aspnet-mvc
//http://cpratt.co/file-uploads-in-asp-net-mvc-with-view-models/
namespace Mina_Bilder.Controllers
{
    [Authorize]
    public class UploadController : Controller
    {
        // GET: Upload


        public ActionResult Index()
        {
            ViewBag.IsUserLoggedIn = false;
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Upload(UploadModel model, HttpPostedFileBase file)
        {
          
                if (file != null)
                {
                    using (ImagesModel db = new ImagesModel())
                    {

                    string path = Path.Combine(Server.MapPath("~/Bilder"),
                                       Path.GetFileName(file.FileName));
                    file.SaveAs(path);


                    Images nModel = new Images();
                    nModel.Titel = model.Titel;
                    nModel.Kommentar = model.Kommentar;
                    nModel.Path = file.FileName;

                    db.Images.Add(nModel);
                    db.SaveChanges();

                    }
                }
            

            return RedirectToAction("Index", "Images");
        }
    }
}

MinaBilder3.0/Views/Images/Index.cshtml
@model List<Images>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@foreach (var item in Model) 
{
   

    <a href="Bilder/@item.Path" data-toggle="lightbox" data-title="@item.Titel"
                         data-footer ="@item.Kommentar"
                         data-gallery ="example-gallery" class="col-sm-4">
                       <img src ="Bilder/@item.Path" class="img-fluid img-style">
                     </a>
}

<script src="//ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"
        integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY"
        crossorigin="anonymous"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js"
        integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB"
        crossorigin="anonymous"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.3/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.0.0/ekko-lightbox.js"></script>
<script>

    //script tillhörande pluginget Lighbox som skapar galleriet som bilderna visas upp i.
    $(document).on('click', '[data-toggle="lightbox"]', function (event) {
        event.preventDefault();
        $(this).ekkoLightbox();
    });

</script>

MinaBilder3.0/Views/Login/Index.cshtml
@model MinaBilder3._0.Models.Credentials



@using (Html.BeginForm())
{

    <div class="form-horizontal register-form">
        <div class="form-group">
            @Html.Label("Användarnamn", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(m => m.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.Username, "", new { @class = "text-danger" })


            </div>
        </div>

        <div class="form-group">
            @Html.Label("Lösenord", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(m => m.Password, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>


        <input class="btn btn-primary col-md-12" type="submit" name="submit" value="Logga in">
    </div>


}
@if (ViewBag.LoggedInFail == true)
{
    <div style="margin-top:120px" class="alert alert-danger">
        <strong>Fel användarnamn eller lösenord!</strong> Var god försök igen.
    </div>
}

MinaBilder3.0/Views/Register/Index.cshtml
@model MinaBilder3._0.Users



<script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.json-2.2.min.js")" type="text/javascript"></script>

@using (Html.BeginForm())
{
   
        <div class="form-horizontal register-form">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.Label("Användarnamn", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.EditorFor(m => m.Username, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(m => m.Username, "", new { @class = "text-danger" })


                </div>
            </div>

            <div class="form-group">
                @Html.Label("Lösenord", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.EditorFor(m => m.Password, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                    @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })


                </div>
            </div>
            <div class="form-group">
                @Html.Label("Lösenord", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.EditorFor(m => m.ConfirmPassword, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                    @Html.ValidationMessageFor(m => m.ConfirmPassword, "", new { @class = "text-danger" })


                </div>
            </div>


            <input class="btn btn-primary col-md-12" type="submit" name="submit" value="Registrera">
        </div>


}

@if (ViewBag.SuccessResult == true)
{
    <div style="margin-top:120px" class="alert alert-success" role="alert"><b>Du har skapat ett konto.</b> Logga in @Html.ActionLink("Här", "Index", "Login")</div>;
}

MinaBilder3.0/Views/Shared/_Layout.cshtml

<!doctype html>
<html lang="en">
<head>
    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <script src="js/bootstrap.js" type="text/javascript"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.1.1.js"
            integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA=" crossorigin="anonymous"></script>
    <!--Latest compiled and minified JavaScript-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <!--För lightboxen som är från http://ashleydw.github.io/lightbox/-->
    <link rel="stylesheet"
          href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.3/css/bootstrap.min.css">
    <link href="//cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.0.0/ekko-lightbox.css" rel="stylesheet">
    <!--Font för menyn-->
    <link href='https://fonts.googleapis.com/css?family=Cinzel' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="css/style.css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"
            integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY"
            crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js"
            integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB"
            crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.3/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.0.0/ekko-lightbox.js"></script>
    <meta charset="UTF-8">
    <link href="~/Content/Site.css" rel="stylesheet" />
    <title>Document</title>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Mina Bilder", "Index", "Start", null, new { @class = "navbar-brand" })


                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation">
                            @Html.ActionLink("Bilder", "Index", "Images")


                        </li>
                        <li role="presentation">
                            @Html.ActionLink("Ladda upp", "Index", "Upload")


                        </li>
                        <li role="presentation">
                            @Html.ActionLink("Logga In", "Index", "Login")


                        </li>
                        <li role="presentation">
                            @Html.ActionLink("Registrera", "Index", "Register")
                        </li>
                        @if (Context.User.Identity.IsAuthenticated)
                        {
                            <li role="presentation" class=" pull-right">
                                @Html.ActionLink("Logga Ut", "LogOut", "Login")
                            </li> }

                    

                    </ul>
                </div>
            </div>
        </nav>
        <script>
            //Sätter class="active" på den aktuella sidan och visar på nav bar-en vilken sida som användaren är inne på.
            $(document).ready(function () {
                var url = window.location;
                // Will only work if string in href matches with location
                $('ul.nav a[href="' + url + '"]').parent().addClass('active');

                // Will also work for relative and absolute hrefs
                $('ul.nav a').filter(function () {
                    return this.href == url;
                }).parent().addClass('active').parent().parent().addClass('active');
            });


        </script>

        <div class="container body-content">
            @RenderBody()

        </div>
    </div>
</body>
</html>

MinaBilder3.0/Views/Start/Index.cshtml



<div class="jumbotron">
    <h1>Mina Bilder</h1>
    <p class="lead">
        Här kan du skapa ett bildgalleri. Registrera dig på länken nedan eller klicka på logga in i
        menyn.
    </p>
    <p><a class="btn btn-lg btn-success" href="register.php" role="button">Registrera dig</a></p>
</div>
<div class="row">
    <div class="offset-md-2 col-md-8">
        <div class="row">
            <a href="http://webbkurs.ei.hv.se/~alba0008/WBP301/notes/bilder/344H.jpg" data-toggle="lightbox"
               data-gallery="example-gallery" class="col-sm-4">
                <img src="http://webbkurs.ei.hv.se/~alba0008/WBP301/notes/bilder/344H.jpg" class="img-fluid">
            </a>
            <a href="http://webbkurs.ei.hv.se/~alba0008/WBP301/notes/bilder/345H.jpg" data-toggle="lightbox"
               data-gallery="example-gallery" class="col-sm-4">
                <img src="http://webbkurs.ei.hv.se/~alba0008/WBP301/notes/bilder/345H.jpg" class="img-fluid">
            </a>
            <a href="http://webbkurs.ei.hv.se/~alba0008/WBP301/notes/bilder/346H.jpg" data-toggle="lightbox"
               data-gallery="example-gallery" class="col-sm-4">
                <img src="http://webbkurs.ei.hv.se/~alba0008/WBP301/notes/bilder/346H.jpg" class="img-fluid">
            </a>
        </div>
        <div class="row">
            <a href="http://webbkurs.ei.hv.se/~alba0008/WBP301/notes/bilder/347H.jpg" data-toggle="lightbox"
               data-gallery="example-gallery" class="col-sm-4">
                <img src="http://webbkurs.ei.hv.se/~alba0008/WBP301/notes/bilder/347H.jpg" class="img-fluid">
            </a>
            <a href="http://webbkurs.ei.hv.se/~alba0008/WBP301/notes/bilder/348H.jpg" data-toggle="lightbox"
               data-gallery="example-gallery" class="col-sm-4">
                <img src="http://webbkurs.ei.hv.se/~alba0008/WBP301/notes/bilder/348H.jpg" class="img-fluid">
            </a>
            <a href="http://webbkurs.ei.hv.se/~alba0008/WBP301/notes/bilder/351H.jpg" data-toggle="lightbox"
               data-gallery="example-gallery" class="col-sm-4">
                <img src="http://webbkurs.ei.hv.se/~alba0008/WBP301/notes/bilder/351H.jpg" class="img-fluid">
            </a>
        </div>
    </div>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"
        integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY"
        crossorigin="anonymous"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js"
        integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB"
        crossorigin="anonymous"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.3/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.0.0/ekko-lightbox.js"></script>
<script>

    $(document).on('click', '[data-toggle="lightbox"]', function (event) {
        event.preventDefault();
        $(this).ekkoLightbox();
    });

</script>

MinaBilder3.0/Views/Upload/Index.cshtml
@model MinaBilder3._0.Models.UploadModel



@using (Html.BeginForm("Upload", "Upload", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-horizontal upload-form">
        <div class="form-group">
            @Html.Label("Titel", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(m => m.Titel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.Titel, "", new { @class = "text-danger" })


            </div>
        </div>

        <div class="form-group">
            @Html.Label("Kommentar", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(m => m.Kommentar, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>

        <div class="form-group form-style">
            <input style="margin-left: 16px;" type="file" name="file" id="imgupload" required>
        </div>
        <input class="btn btn-primary" type="submit" name="submit" id="btn-upload"
               value="Ladda upp">
    </div>
}
<img id="uploadPreview" class="pull-right img-preview" width="600" height="400" src="#" alt="preview image" />




<script>
    //http://stackoverflow.com/questions/1601455/how-to-check-file-input-size-with-jquery
    //ett script som kollar storleken på bilden och om bilden är större än 2 mb visas en alertruta med info att bilden inte får vara större än 2 mb.
    //samtidigt så disablas knappen som laddar upp bilden.
    $('#imgupload').bind('change', function () {
        var size = this.files[0].size;
        if (size > 2097152) {
            document.getElementById("btn-upload").disabled = true;
            alert("Bilden är för stor. Välj en ny som är mindre än 2mb.")
        } else {
            document.getElementById("btn-upload").disabled = false;
        }



    });

    //Script som förhandsvisar bilden som användaren vill ladda upp. Taget från http://stackoverflow.com/questions/4459379/preview-an-image-before-it-is-uploaded
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $("#uploadPreview").attr("src", e.target.result);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#imgupload").change(function () {
        readURL(this);
    });


</script> 